config/routes.rb
Rails.application.routes.draw do
  #get 'welcome/index'
  #get "categorys/new"
  #post "categorys" => "categorys#create"
  #get "categorys/:id" => "categorys#show"
  #get "categorys" => "categorys#index"
  #get "categorys/:id/edit" => "categorys#edit"
  #put "categorys/:id" => "categorys#update"
  #delete "categorys/:id" => "categorys#destroy"


    resources :categorys do
    	resources :songs
    end

  root :to => "welcome#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord


has_many :songs, :dependent => :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController

def index
  @categorys = Category.all
end

def new
@category = Category.new
end

def edit
  @category = Category.find(params[:id])
end

def create
  @category = Category.new(category_params)

 if @category.save
  redirect_to :action => :show, :id => @category.id
	else
		render 'new'
	end
end

def show
  @category = Category.find(params[:id])
end

def update
  @category = Category.find(params[:id])

  if @category.update_attributes(category_params)
    redirect_to :action => :show, :id => @category.id
  else
    render 'edit'
  end
end


def destroy
  @category = Category.find(params[:id])
  @category.destroy

  redirect_to :action => :index
end

private

def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  
 def index
   category = Category.find(category_params[:category_id])
   @songs = category.songs
end

  

  def create
    @category = Category.find(params[:category_id])
    @song = @category.songs.create(song_params)
    redirect_to category_path(@category)
  end

 def destroy
    @category = Category.find(params[:category_id])
    @song = @category.songs.find(params[:id])
    @song.destroy
    redirect_to category_path(@category)
  end

  private

  def song_params
    params.require(:song).permit(:name, :artist, :album )
 	end

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categorys/edit.html.erb
<h1>Editing Category</h1>

<%= form_for :category, :url => { :action => :update, :id => @category.id },
:method => :put do |c| %>
  <% if @category.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= c.label :name %><br>
    <%= c.text_field :name %>
  </p>

  
  <p>
    <%= c.submit %>
  </p>
<% end %>

<%= link_to 'Back', :action => :index %>

app/views/categorys/index.html.erb
<table>
  <tr>
    <th>Name</th>
   
    
  </tr>

<% @categorys.each do |c| %>
  <tr>
    <td><%= c.name %></td>
    
    <td><%= link_to 'Show', category_path(c) %></td>
    <td><%= link_to 'Edit', edit_category_path(c) %></td>
    <td><%= link_to 'Destroy', category_path(c), :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/categorys/new.html.erb
<h1>New Category</h1>

<%= form_for :category, :url => { :action => :create } do |c| %>
  <% if @category.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= c.label :Name %><br>
    <%= c.text_field :name %>
  </p>


  <p>
    <%= c.submit %>
  </p>
<% end %>

<%= link_to 'Back', :action => :index %>

app/views/categorys/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<h2>Song</h2>
<% @category.songs.each do |c| %>
  <p>
    <strong>Name:</strong>
    <%= c.name %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= c.artist %>
  </p>
  <p>
    <strong>Album:</strong>
    <%= c.album %>
  </p>
  <p>
  <%= link_to 'Eliminar Cancion', category_song_path(c),
               :method => :delete,
               :data => { :confirm => '¿Estás seguro?' } %>
</p>
<% end %>


<h2>Add a Song:</h2>
<%= form_for([@category, @category.songs.build]) do |c| %>
  <p>
    <%= c.label :name %><br />
    <%= c.text_field :name %>
  </p>
  <p>
    <%= c.label :artist %><br />
    <%= c.text_area :artist %>
  </p>
   <p>
    <%= c.label :album %><br />
    <%= c.text_area :album %>
  </p>
  <p>
    <%= c.submit %>
  </p>
<% end %>

<%= link_to 'Edit Category', edit_category_path(@category) %> |
<%= link_to 'Back to Categorys', categorys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsmusic7</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails</h1>

<%= link_to "Music", categorys_path %>